### ISSUE TITLE
Contributors without articles

### ISSUE THREAD

**Issue by tbl73** [VictorianResearchWeb/TheCurranIndex#10]
When looking through the original version of the website, there's a great deal of bibliographical information displayed towards the end (see example image below).  That doesn't appear to be information that would be included in the article listings that are meant to form the bulk of the site, so I wanted to find out if it is information that should be included, and if so, where does it belong? @gsimons1946 , can you let me know what you have in mind for this info?

![image](https://user-images.githubusercontent.com/16854029/29172909-7e2e4ff2-7daf-11e7-82bf-975611f2fd2a.png)

**Comment by gsimons1946** [comment]
This information is in the Curran Index database. Some of the names in the contributor file don't have any associated articles. Instead, there is relevant information in the contributors.comment field. If one selects that contributor, his or her information header should show on screen, with no associated articles.

**Comment by saracarl** [comment]
I think we can close this -- the site is working as designed, it's just that the data is different than most.  Concur, @gsimons1946 ?

**Comment by benwbrum** [comment]
Gary agrees.  closing.
