### ISSUE TITLE
Static pages and links

### ISSUE THREAD

**Issue by tbl73** [VictorianResearchWeb/TheCurranIndex#3]
Add links to additional static pages for the site, as well as any necessary links to other sites. (I'm thinking primarily of the Victorian research web site.)

**Comment by tbl73** [comment]
One thing to think about (in terms of design) is whether the additional pages would be displayed better as links or additional tabs of some kind.

**Comment by saracarl** [comment]
Perhaps a single tab -- "articles" and then links within it?  

And with a site like this one, it's always hard to figure out what to put on the "main" page before you do any searches.  There's probably some boilerplate about The Curran Index we could use, perhaps a bit of "how to" (search/cite)...  But worth thinking about.  Perhaps another issue.
