### ISSUE TITLE
home screen: Ordering of Articles

### ISSUE THREAD

**Issue by saracarl** [VictorianResearchWeb/TheCurranIndex#33]
the list of articles appear to be ordered by periodical, volume, page start, and page end, which almost always produces an appropriate chronological ordering. Sometimes, however, in the middle of the run of a periodical the volume number is reset by the publisher, so volume 1 can actually come out after volume 7. We see this problem in the current CI for the Monthly Repository. A possible solution would be to order based on periodicals.abbreviation, articles.issue_number (which is always present but never displayed), articles.page_start, and articles.page_end. This would always give the right order.

**Comment by benwbrum** [comment]
In the current version of the database, this can be duplicated by filtering articles on _Monthly Review_ and _prose_ article types, then navigating to page *4*, where the break is visible:

```
 MRep, High and Low Life in Italy. No. IX, 226 - 281, Apr 1838, Walter Savage Landor, Marked in Leigh Hunt presentation copy; see F. Mineka, The Dissidence of Dissent (1944): 425-8. (03/18)

MRep, Rumuneration of Authors, 283 - 287, Apr 1838, Unknown, Signed an author's son. (03/18)

MRep, New Year's Morning, 1 - 4, Jan 1830, Emily Taylor, From marked file in British Library; see Mineka, The Dissidence of Dissent (1944): 400-425. (03/18)

MRep, On the Progress of Unitarianism in Great Britain, 10 - 15, Jan 1830, Richard Wright, Dated Coningsby, Nov. 24, 1829; signed R. Wright. (03/18)
```

**Comment by benwbrum** [comment]
The code being generated by the two order scope methods appears to be this:
```
 ORDER BY `periodicals`.`title` ASC, `articles`.`volume` ASC, `articles`.`issue_number` ASC, `articles`.`page_start` ASC, `articles`.`page_end` ASC
```
