### ISSUE TITLE
contributors: filter by periodicals

### ISSUE THREAD

**Issue by saracarl** [VictorianResearchWeb/TheCurranIndex#37]
As on the home screen, there will be a filter for periodicals to the left of the main display box. By selecting a given periodical one will be able to display a list of all the contributors to that periodical. If multiple periodicals are selected there must also be a way of ascertaining whether the list should show contributors who have articles in all the selected periodicals or in any of the selected periodicals.

**Comment by benwbrum** [comment]
Gary would like to have both options.  Switch?  

Investigate.

Use Case:  So if I'm researching women poets in the Victorian era, I may want to select 3 periodicals and see all contributors to those three periodicals (perhaps that meet other criteria, like gender as well) OR I may want to see just contributors that were published in all 3 periodicals I selected.  Researcher needs to be able to do both.
