### ISSUE TITLE
contributors:  search comments

### ISSUE THREAD

**Issue by saracarl** [VictorianResearchWeb/TheCurranIndex#39]
Instead of Title Search there should be a search capability for the contributors.comment field (so, for example, one could get a list of individuals who were clerics, or journalists, or had another specific term associated with them.

**Comment by benwbrum** [comment]
"notes"?

The contributor database Gary uses has an unlimited-length memo field which is used for information like 'books they have written', alternative titles like 'clergy', 'attorney', etc, which does not lend itself to particular fields.  Full-text search on this is valuable, but what do we call it?
