### ISSUE TITLE
contributors: search by name?

### ISSUE THREAD

**Issue by saracarl** [VictorianResearchWeb/TheCurranIndex#40]
@gsimons1946, you didn't include searching by name, but I think we should consider that.  Otherwise you have to page & scroll through a very long alphabetical list to get to a specific person.  Is that OK?  Is the contributor screen only used for filtered groups of contributors?

**Comment by benwbrum** [comment]
Searching by name is desirable.  The information that appears on the article screen when hovering over a contributor is hard to extract via cut-and-pasted or elsewhere.

Researchers might want to see all the articles Maria Crawford contributed (subject to other criteria.) Or Maria and Luisa...
