### ISSUE TITLE
Google analytics for CI

### ISSUE THREAD

**Issue by saracarl** [VictorianResearchWeb/TheCurranIndex#50]
Is there a way to track the number of hits the Curran Index receives and to have access to that information?

**Comment by saracarl** [comment]
Yes!  Please sign up for a Google Analytics account and we'll embed the google analytics code in everypage so you can get more numbers than you'll know what to do with.  :) 

https://www.google.com/analytics

**Comment by benwbrum** [comment]
Give us access to your analytics account after you create it...
